GET http://localhost:3000/users

GET http://localhost:3000/users/#

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

# {
#     "firstName": "Sara",
#     "lastName": "Dawson",
#     "email": "sd@gmail.com",
#     "favoriteColor":"Blue",
#     "birthday": "6/12/1999"
# }

# PUT http://localhost:3000/users/# HTTP/1.1
# content-type: application/json
# {
#     "firstName": "Sara",
#     "lastName": "Dawson",
#     "email": "sd@gmail.com",
#     "favoriteColor":"Blue",
#     "birthday": "6/12/1999"
# }